INSERT INTO pokemon
    (dex, species, photo, about, price)
Values
    ('001', 'Bulbasaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png', 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.', 12.70),
    ('002', 'Ivysaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 10.37),
    ('003', 'Venausaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png', 'Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 101.47),
    ('004', 'Charmander', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png', 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.', 2.62),
    ('005', 'Charmeleon', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png', 'It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.', 2.44),
    ('006', 'Charizard', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png', 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.', 31.24),
    ('007', 'Squirtle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png', 'When it retracts its long neck into its shell, it squirts out water with vigorous force.', 3.77),
    ('008', 'Wartortle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png', 'It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.', 6.55),
    ('009', 'Blastoise', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png', 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.', 97.34),
    ('010', 'Caterpie', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png', 'For protection, it releases a horrible stench from the antenna on its head to drive away enemies.', 3.82),
    ('011', 'Metapod', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png', 'It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.', ),
    ('012', 'Butterfree', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png', 'In battle, it flaps its wings at great speed to release highly toxic dust into the air.', ),
    ('013', 'Weedle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png', 'Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.'),
    ('014', 'Kakuna', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png', 'Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.'),
    ('015', 'Beedrill', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png', 'It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.'),
    ('016', 'Pidgey', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png', 'Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.'),
    ('017', 'Pidgeotto', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png', 'This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.'),
    ('018', 'Pidgeot', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png', 'This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.'),
    ('019', 'Rattata', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png', 'Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.'),
    ('020', 'Raticate', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png', 'Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.'),
    ('021', 'Spearow', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png', 'Inept at flying high. However, it can fly around very fast to protect its territory.'),
    ('022', 'Fearow', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png', 'A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.'),
    ('023', 'Ekans', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png', 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.'),
    ('024', 'Arbok', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png', 'The frightening patterns on its belly have been studied. Six variations have been confirmed.'),
    ('025', 'Pikachu', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png', 'Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.'),
    ('026', 'Raichu', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png', 'Its long tail serves as a ground to protect itself from its own high-voltage power.'),
    ('027', 'Sandshrew', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png', 'It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body.'),
    ('028', 'Sandslash', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png', 'The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched.');