INSERT INTO pokemon
    (dex, species, photo, about, price)
Values
    ('001', 'Bulbasaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png', 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.', '12.70'),
    ('002', 'Ivysaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', '10.37'),
    ('003', 'Venausaur', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png', 'Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', '102.13'),
    ('004', 'Charmander', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png', 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.', ),
    ('005', 'Charmeleon', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png', 'It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.', ),
    ('006', 'Charizard', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png', 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.', ),
    ('007', 'Squirtle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png', 'When it retracts its long neck into its shell, it squirts out water with vigorous force.', ),
    ('008', 'Wartortle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png', 'It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.', ),
    ('009', 'Blastoise', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png', 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.', ),
    ('010', 'Caterpie', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png', '', ),
    ('011', 'Metapod', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png', '', ),
    ('012', 'Butterfree', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png', '', ),
    ('013', 'Weedle', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png', ),
    ('014', 'Kakuna', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png', ),
    ('015', 'Beedrill', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png', ),
    ('016', 'Pidgey', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png', ),
    ('017', 'Pidgeotto', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png', ),
    ('018', 'Pidgeot', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png', ),
    ('019', 'Rattata', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png', ),
    ('020', 'Raticate', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png', ),
    ('021', 'Spearow', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png', ),
    ('022', 'Fearow', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png', ),
    ('023', 'Ekans', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png', ),
    ('024', 'Arbok', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png', ),
    ('025', 'Pikachu', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png', ),
    ('026', 'Raichu', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png', ),
    ('027', 'Sandshrew', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png', ),
    ('028', 'Sandslash', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png', );